# Generated by Django 2.1.2 on 2018-10-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrito',
            name='estado',
        ),
        migrations.DeleteModel(
            name='perrito',
        ),
    ]
