# Generated by Django 2.1.2 on 2018-10-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescate', '0003_perrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrito',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perrito',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='perrito',
            name='nombrePerro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perrito',
            name='razaP',
            field=models.CharField(max_length=50),
        ),
    ]
