# Generated by Django 2.0.9 on 2018-11-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescate', '0005_auto_20181026_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('códigoProducto', models.IntegerField()),
                ('nombreProducto', models.CharField(max_length=100)),
                ('descripciónProducto', models.TextField()),
                ('precioProducto', models.IntegerField()),
                ('imagen', models.FileField(upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='perrito',
            name='estado',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='perrito',
        ),
    ]
