# Generated by Django 2.1.2 on 2018-10-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('nombres', models.CharField(max_length=50)),
                ('apPaterno', models.CharField(max_length=30)),
                ('apMaterno', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('dvRut', models.CharField(max_length=1)),
                ('fNacimiento', models.DateField()),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
